# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 16:59
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mozix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(choices=[('DOCE', 'Doces'), ('REFRI', 'Bebidas'), ('PETI', 'Petiscos'), ('SALG', 'Salgados'), ('ASSA', 'Assados')], max_length=6)),
                ('titulo', models.CharField(max_length=100)),
                ('apresentacao', models.TextField()),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('datapublicacao', models.DateTimeField()),
            ],
        ),
    ]
