# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mozix',
            name='tipos',
            field=models.CharField(choices=[('DOCE', 'Comidas'), ('REFRI', 'Bebidas'), ('PETI', 'Petiscos'), ('SALG', 'Salgados'), ('ASSA', 'Assados')], max_length=6),
        ),
    ]
