# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozi', '0002_auto_20180117_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mozix',
            name='tipos',
            field=models.CharField(choices=[('COMIDA', 'Comidas'), ('BEBIDA', 'Bebidas'), ('PETI', 'Petiscos'), ('SALG', 'Salgados'), ('ASSA', 'Assados'), ('UNICA', 'Unica')], max_length=6),
        ),
    ]
