# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-14 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mozi', '0003_auto_20180123_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='mozix',
            name='validade',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
