# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozi', '0004_mozix_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mozix',
            name='tipos',
            field=models.CharField(choices=[('COMIDA', 'Comidas'), ('BEBIDA', 'Bebidas'), ('PETI', 'Petiscos'), ('SALG', 'Salgados'), ('ASSA', 'Assados'), ('INI', 'Inicial')], max_length=6),
        ),
    ]
