# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 13:28
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petmania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(choices=[('COMER', '1'), ('EDUCA', '2'), ('ACESS', '3'), ('HIGI', '4'), ('ANTI', '5')], max_length=6)),
                ('titulo', models.TextField()),
                ('apresentacao', models.TextField()),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('datapublicacao', models.DateTimeField()),
            ],
        ),
    ]
