# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmania',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
