# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20171221_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmania',
            name='tipos',
            field=models.CharField(choices=[('COMER', 'Alimentacao'), ('EDUCA', 'Educacau'), ('ACESS', 'Acessorios'), ('HIGI', 'Higienizacao'), ('ANTI', 'Antiparasitas')], max_length=6),
        ),
    ]
