# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20171221_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmania',
            name='validade',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petmania',
            name='tipos',
            field=models.CharField(choices=[('COMER', 'Alimentacao'), ('EDUCA', 'Educacau'), ('ACESS', 'Acessorios'), ('HIGI', 'Higienizacao'), ('ANTI', 'Antiparasitas'), ('INI', 'Inicial')], max_length=6),
        ),
    ]
