# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acai',
            name='validade',
            field=models.DateTimeField(blank=True),
        ),
    ]
