# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acai', '0005_auto_20180303_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acai',
            name='validade',
            field=models.DateField(null=True),
        ),
    ]
