# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acai', '0006_auto_20180324_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acai',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
