# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandubas', '0002_auto_20180324_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandubas',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
